name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-image-name:latest .
          docker push your-image-name:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f compose.yml up -d

      - name: Clean up
        run: |
          docker system prune -f
